server:
  port: 80
spring:
  datasource:
    username: postgres
    password: Sobirov0717
    url: jdbc:postgresql://localhost:5432/revolusion_intern_demo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'snurmuhammad85@gmail.com'
    password: 'ydjdeuzztivhuvun'
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  admin:
    email: "snurmuhammad85@gmail.com"
    password: "Admin.123@"
    fullName: "Nurmukhammad"

  jwt:
    secretKey: "55d2430e17864da8db7h8dbd64a63777be5c1a7f06k92197c9b8113a3b552l60"
    expireDays: 7